// App Configuration
export interface AppConfig {
  language: 'en' | 'zh-TW';
  theme: 'mistBlue' | 'lavenderSmoke' | 'roseDust' | 'oliveGray' | 'sandBeige' | 'seafoamGreen' | 'cloudGray' | 'plumNight' | 'mintFrost' | 'coralClay' | 'sageGreen' | 'denimBlue' | 'mochaCream' | 'tealOcean' | 'amberDawn' | 'charcoalViolet' | 'icePink' | 'skyGray' | 'forestShadow' | 'inkBlack';
}

// Tab Icon Configuration
export interface TabIconConfig {
  localSource: any;       // Local image source (完全離線)
}

// Language translations
export const translations = {
  en: {
    // Tab labels
    home: 'Home',
    check: 'Passbook',
    add: 'Add',
    statistics: 'Statistics',
    settings: 'Settings',
    
    // Home screen
    financialOverview: 'Financial Overview',
    totalBalance: 'Total Balance',
    myAccounts: 'My Accounts',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    noTransactions: 'No transactions yet',
    noTransactionsSubtext: 'Tap "Add" to start tracking',
    income: 'Income',
    expense: 'Expense',
    
    // Add screen
    addTransaction: 'Add Transaction',
    amount: 'Amount',
    note: 'Note',
    noteExample: 'Note (e.g., Lunch, Freelance Fee)',
    selectPassbook: 'Select Passbook',
    selectCategory: 'Select Category',
    autoAllocate: 'Auto-allocate by ratio',
    pleaseSetRatio: 'Please set ratio in settings first',
    cancel: 'Cancel',
    complete: 'Complete',
    errorTitle: 'Error',
    pleaseEnterValidAmount: 'Please enter a valid amount',
    ratioNotSet: 'Ratio Not Set',
    pleaseSetRatioFirst: 'Please set the ratio for each passbook in "Ratio Settings" first',
    goToSettings: 'Go to Settings',
    ratioError: 'Ratio Error',
    ratioMustBe100: 'The sum of all passbook ratios must be 100%\nCurrent sum: ',
    transactionAdded: 'Transaction added successfully',
    addFailed: 'Failed to add transaction',
    food: 'Food',
    transport: 'Transportation',
    entertainment: 'Entertainment',
    shopping: 'Shopping',
    utilities: 'Utilities',
    other: 'Other',
    
    // Check screen
    passbook: 'Passbook',
    balance: 'Balance',
    incomeLabel: 'Income',
    expensesLabel: 'Expenses',
    balanceLabel: 'Balance',
    
    // Statistics screen
    monthlyStatistics: 'Monthly Statistics',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    netSavings: 'Net Savings',
    
    // Settings screen
    passbookManagement: 'Passbook Management',
    ratioSettings: 'Ratio Settings',
    feedback: 'Feedback',
    language: 'Language',
    theme: 'Theme',
    clearData: 'Clear Data',
    about: 'About',
    
    // Common
    delete: 'Delete',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    save: 'Save',
    
    // Additional
    incomeAllocatedTo: 'Income allocated to',
    allTransactions: 'All Transactions',
    deleteTransaction: 'Delete Transaction',
    confirmDelete: 'Are you sure you want to delete',
    transactionDeleted: 'Transaction deleted',
    deleteFailed: 'Delete failed',
    
    // Statistics Screen
    monthlyIncomeVsExpenses: 'Monthly Income vs. Expenses',
    netBalance: 'Net Balance',
    loading: 'Loading...',
    totalsByAccount: 'Totals by Account',
    accounts: 'accounts',
    allAccounts: 'All Accounts',
    
    // CheckScreen
    monthlySummary: 'Monthly Summary',
    noDataForMonth: 'No data for this month',
    displaysMonthlyInfo: 'Displays monthly income, expenses, and balance for each passbook',
    
    // Settings Screen
    managePassbooks: 'Manage Passbooks',
    adjustRatio: 'Adjust Ratio',
    selectLanguage: 'Select Language',
    selectTheme: 'Select Theme',
    mistBlue: 'Mist Blue',
    lavenderSmoke: 'Lavender Smoke',
    roseDust: 'Rose Dust',
    oliveGray: 'Olive Gray',
    sandBeige: 'Sand Beige',
    seafoamGreen: 'Seafoam Green',
    cloudGray: 'Cloud Gray',
    plumNight: 'Plum Night',
    mintFrost: 'Mint Frost',
    coralClay: 'Coral Clay',
    sageGreen: 'Sage Green',
    denimBlue: 'Denim Blue',
    mochaCream: 'Mocha Cream',
    tealOcean: 'Teal Ocean',
    amberDawn: 'Amber Dawn',
    charcoalViolet: 'Charcoal Violet',
    icePink: 'Ice Pink',
    skyGray: 'Sky Gray',
    forestShadow: 'Forest Shadow',
    inkBlack: 'Ink Black',
    clearDataTitle: 'Clear Data',
    clearDataMessage: 'Are you sure you want to clear all transaction data? This action cannot be undone!',
    allDataCleared: 'All data has been cleared',
    aboutFinora: 'About Finora',
    aboutMessage: 'Finora App v1.0.0\n\nAn app to help you manage your finances\n\nDeveloped by Serelix Studio Team\nWebsite: www.serelix.xyz\n\n© 2025 Serelix Studio',
    ok: 'OK',
    
    // Custom Theme Screens
    customTheme: 'Custom Theme',
    myThemes: 'My Themes',
    submittedThemes: 'Submitted Themes',
    themeProposals: 'Theme Proposals',
    createYourOwn: 'Create your own style',
    viewSavedThemes: 'View saved themes',
    checkReviewStatus: 'Check review status',
    createTheme: 'Create Theme',
    saveTheme: 'Save Theme',
    submitForReview: 'Submit for Review',
    resetColors: 'Reset Colors',
    themeName: 'Theme Name',
    themeNameRequired: 'Theme name is required',
    themeEmoji: 'Theme Emoji',
    emojiOptional: 'Emoji (Optional)',
    colorPalette: 'Color Palette',
    background: 'Background',
    cardColor: 'Card',
    cardAltColor: 'Card Alt',
    glassColor: 'Glass',
    textColor: 'Text',
    textSecondaryColor: 'Secondary Text',
    primaryColor: 'Primary',
    primarySoftColor: 'Primary Soft',
    accentColor: 'Accent',
    borderColor: 'Border',
    bottomBarColor: 'Bottom Bar',
    successColor: 'Success',
    errorColor: 'Error',
    preview: 'Preview',
    themeSaved: 'Theme saved successfully!',
    themeSaveFailed: 'Failed to save theme',
    themeSubmitted: 'Thank you for your submission! We will review your theme.',
    themeSubmitFailed: 'Failed to submit, please try again',
    ensureValidColors: 'Please ensure all colors are valid',
    deleteTheme: 'Delete Theme',
    deleteThemeConfirm: 'Are you sure you want to delete "{name}"?',
    themeDeleted: 'Theme deleted',
    applyTheme: 'Apply Theme',
    applyThemeComingSoon: 'Custom theme application coming soon!',
    noSavedThemes: 'No saved themes yet',
    noSubmittedThemes: 'No submitted themes yet',
    createAndSubmit: 'Create a theme and submit it for review!',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    reviewPending: '⏳ Your theme is under review, please wait',
    submit: 'Submit',
    submitting: 'Submitting...',
    
    // Ratio Settings Screen
    ratioSettingsTitle: 'Ratio Settings',
    autoDistribution: 'Auto Distribution',
    setRatio: 'Set the distribution ratio for each passbook',
    totalRatio: 'Total Ratio',
    adjustRatioTooltip: 'Adjust the sliders so the total equals 100%',
    ratioSaved: 'Ratio settings saved',
    ratioSaveFailed: 'Failed to save ratio settings',
  },
  'zh-TW': {
    // Tab labels
    home: '首頁',
    check: '存摺',
    add: '新增',
    statistics: '統計',
    settings: '設定',
    
    // Home screen
    financialOverview: '財務總覽',
    totalBalance: '總餘額',
    myAccounts: '我的帳戶',
    recentTransactions: '最近記帳',
    viewAll: '查看全部',
    noTransactions: '尚無記帳記錄',
    noTransactionsSubtext: '點擊下方「新增」按鈕開始記帳',
    income: '收入',
    expense: '支出',
    
    // Add screen
    addTransaction: '新增記帳',
    amount: '金額',
    note: '備註',
    noteExample: '備註（例如：午餐、接案收入）',
    selectPassbook: '選擇存摺',
    selectCategory: '選擇類別',
    autoAllocate: '按比例自動分配',
    pleaseSetRatio: '請先在設定中設定比例',
    cancel: '取消',
    complete: '完成',
    errorTitle: '錯誤',
    pleaseEnterValidAmount: '請輸入有效金額',
    ratioNotSet: '未設定比例',
    pleaseSetRatioFirst: '請先在「比例設定」頁面設定各存摺的比例',
    goToSettings: '前往設定',
    ratioError: '比例錯誤',
    ratioMustBe100: '所有存摺的比例總和必須為 100%\n目前總和為 ',
    transactionAdded: '記帳新增成功',
    addFailed: '新增失敗',
    food: '飲食',
    transport: '交通',
    entertainment: '娛樂',
    shopping: '購物',
    utilities: '帳單',
    other: '其他',
    
    // Check screen
    passbook: '存摺',
    balance: '餘額',
    incomeLabel: '收入',
    expensesLabel: '支出',
    balanceLabel: '餘額',
    
    // Statistics screen
    monthlyStatistics: '月度統計',
    totalIncome: '總收入',
    totalExpense: '總支出',
    netSavings: '淨儲蓄',
    
    // Settings screen
    passbookManagement: '存摺管理',
    ratioSettings: '比例設定',
    feedback: '意見反饋',
    language: '語言',
    theme: '主題',
    clearData: '清除資料',
    about: '關於',
    
    // Common
    delete: '刪除',
    confirm: '確認',
    success: '成功',
    error: '錯誤',
    save: '儲存',
    
    // Additional
    incomeAllocatedTo: '收入分配至',
    allTransactions: '所有記帳',
    deleteTransaction: '刪除記帳',
    confirmDelete: '確定要刪除',
    transactionDeleted: '記帳已刪除',
    deleteFailed: '刪除失敗',
    
    // Statistics Screen
    monthlyIncomeVsExpenses: '月度收入與支出',
    netBalance: '淨餘額',
    loading: '載入中...',
    totalsByAccount: '各帳戶總計',
    accounts: '個帳戶',
    allAccounts: '所有帳戶',
    
    // CheckScreen
    monthlySummary: '月度摘要',
    noDataForMonth: '本月無資料',
    displaysMonthlyInfo: '顯示各存摺的月度收入、支出與餘額',
    
    // Settings Screen
    managePassbooks: '管理存摺',
    adjustRatio: '調整比例',
    selectLanguage: '選擇語言',
    selectTheme: '選擇主題',
    mistBlue: '霧藍',
    lavenderSmoke: '煙燻薰衣草',
    roseDust: '玫瑰塵',
    oliveGray: '橄欖灰',
    sandBeige: '沙米色',
    seafoamGreen: '海泡綠',
    cloudGray: '雲灰',
    plumNight: '李紫夜',
    mintFrost: '薄荷霜',
    coralClay: '珊瑚陶',
    sageGreen: '鼠尾草綠',
    denimBlue: '丹寧藍',
    mochaCream: '摩卡奶油',
    tealOcean: '青綠海',
    amberDawn: '琥珀晨',
    charcoalViolet: '炭紫',
    icePink: '冰粉',
    skyGray: '天空灰',
    forestShadow: '森林影',
    inkBlack: '墨黑',
    clearDataTitle: '清除資料',
    clearDataMessage: '確定要清除所有記帳資料嗎？此操作無法撤銷！',
    allDataCleared: '所有資料已清除',
    aboutFinora: '關於 Finora',
    aboutMessage: 'Finora App v1.0.0\n\n幫助您管理財務的應用程式\n\nSerelix Studio Team 開發\n官網: www.serelix.xyz\n\n© 2025 Serelix Studio',
    ok: '確定',
    
    // Custom Theme Screens
    customTheme: '自訂主題',
    myThemes: '我的主題',
    submittedThemes: '提交的主題',
    themeProposals: '提交的主題',
    createYourOwn: '創造你的專屬風格',
    viewSavedThemes: '查看已儲存的主題',
    checkReviewStatus: '查看審核狀態',
    createTheme: '創建主題',
    saveTheme: '儲存主題',
    submitForReview: '提交審核',
    resetColors: '重置顏色',
    themeName: '主題名稱',
    themeNameRequired: '請輸入主題名稱',
    themeEmoji: '主題圖示',
    emojiOptional: '圖示（選填）',
    colorPalette: '調色盤',
    background: '背景色',
    cardColor: '卡片色',
    cardAltColor: '卡片輔色',
    glassColor: '玻璃色',
    textColor: '文字色',
    textSecondaryColor: '次要文字色',
    primaryColor: '主色',
    primarySoftColor: '主色柔和',
    accentColor: '強調色',
    borderColor: '邊框色',
    bottomBarColor: '底欄色',
    successColor: '成功色',
    errorColor: '錯誤色',
    preview: '預覽',
    themeSaved: '主題儲存成功！',
    themeSaveFailed: '儲存失敗',
    themeSubmitted: '感謝您的投稿！我們會審核您的主題。',
    themeSubmitFailed: '投稿失敗，請稍後再試',
    ensureValidColors: '請確認所有顏色格式正確',
    deleteTheme: '刪除主題',
    deleteThemeConfirm: '確定要刪除「{name}」嗎？',
    themeDeleted: '主題已刪除',
    applyTheme: '套用主題',
    applyThemeComingSoon: '自訂主題功能尚未完成，敬請期待！',
    noSavedThemes: '尚未儲存任何主題',
    noSubmittedThemes: '尚未提交任何主題',
    createAndSubmit: '創建一個主題並提交審核吧！',
    pending: '審核中',
    approved: '已通過',
    rejected: '未通過',
    reviewPending: '⏳ 您的主題正在審核中，請耐心等候',
    submit: '提交',
    submitting: '提交中...',
    
    // Ratio Settings Screen
    ratioSettingsTitle: '比例設定',
    autoDistribution: '自動分配',
    setRatio: '設定各存摺的分配比例',
    totalRatio: '總比例',
    adjustRatioTooltip: '調整滑桿使總和等於 100%',
    ratioSaved: '比例設定已儲存',
    ratioSaveFailed: '儲存比例設定失敗',
  },
};

// Tab icons - using local PNG icons only
export const tabIcons: Record<string, TabIconConfig> = {
  home: {
    localSource: require('../../assets/icons/home.png'),
  },
  check: {
    localSource: require('../../assets/icons/passbook.png'),
  },
  add: {
    localSource: require('../../assets/icons/more.png'),
  },
  statistics: {
    localSource: require('../../assets/icons/bar-chart.png'),
  },
  settings: {
    localSource: require('../../assets/icons/settings.png'),
  },
};
